name: Build Windows Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (YY.MM.N format, e.g. 26.4.1)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Ninja
        uses: turtlesec-no/get-ninja@main

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "6.10.2"
          host: windows
          target: desktop
          arch: "win64_msvc2022_64"
          modules: "qtwebengine qtwebchannel qtpositioning qtmultimedia qtsvg"

      - name: Add Qt bin to PATH
        shell: powershell
        run: |
          $qtbin = "D:/a/NullA-Browser/Qt/6.10.2/msvc2022_64/bin"
          $env:PATH = "$qtbin;$env:PATH"

      - name: Configure CMake
        shell: cmd
        run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="D:/a/NullA-Browser/Qt/6.10.2/msvc2022_64" -DMOC_EXECUTABLE="D:/a/NullA-Browser/Qt/6.10.2/msvc2022_64/bin/moc.exe" -DNULLA_VERSION="${{ github.event.inputs.version }}"

      - name: Build
        run: cmake --build build --config Release

      - name: Prepare deploy folder
        shell: powershell
        run: |
          if (Test-Path "build/NullA") { Remove-Item -Recurse -Force build/NullA }
          if (Test-Path "build/NullA_Out") { Remove-Item -Recurse -Force build/NullA_Out }

          mkdir build/NullA_Out
          Get-ChildItem -Path build -Filter "NullA.exe" -Recurse | Where-Object { $_.FullName -notlike "*NullA_Out*" } | Copy-Item -Destination build/NullA_Out/

          Move-Item build/NullA_Out build/NullA

      - name: Deploy Qt into package folder
        run: windeployqt --release --no-translations --dir build/NullA build/NullA/NullA.exe

      - name: Zip build
        shell: powershell
        run: |
          tar -a -c -f NullA-Windows.zip -C build NullA

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: NullA v${{ github.event.inputs.version }}
          prerelease: false
          files: NullA-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
