; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only
;
; This is an ONLINE INSTALLER: it does not embed the browser's files.
; Instead, it downloads the latest NullA-Windows.zip from GitHub at
; install time and extracts it. This means:
;   - You compile this .iss file once and reuse the same Setup.exe forever.
;   - You do NOT need to rebuild it for every new release.
;   - An internet connection is required at install time.
;
; MyAppVersion is intentionally a static label ("Rolling Release") rather
; than a real version number, since this installer always fetches whatever
; the latest GitHub release is at install time not a fixed version number
; here would go stale and be misleading.

#define MyAppName "NullA Browser"
#define MyAppVersion "Rolling Release"
#define MyAppPublisher "Electus Progressive Liberation Software"
#define MyAppURL "https://epls.itch.io/"
#define MyAppExeName "NullA.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

; GitHub's "latest" download link always resolves to the newest release's
; asset with this exact name, so we never need to know the version number
; in advance.
#define DownloadUrl "https://github.com/EPLS-collective/NullA-Browser/releases/latest/download/NullA-Windows.zip"

#expr EmitLanguagesSection

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; DO NOT CHANGE, must stay fixed so existing installs can be updated in place.
AppId={{842598F1-5A1C-45CC-91CD-AE6A7CCBF379}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=..\LICENSE.txt
OutputDir=dist
OutputBaseFilename=NullA Setup
SetupIconFile=..\resources\nulla_icon.ico
SolidCompression=yes
WizardStyle=modern
; Since files are downloaded at install time instead of being embedded,
; Inno Setup can't calculate the install size from [Files] (there isn't
; one). This tells the "Select Destination Location" screen a realistic
; size instead of just the size of this small bootstrapper exe.
; Adjust this if the real extracted size changes a lot - check with:
;   du -sb NullA/     (on the extracted Linux/Windows package folder)
ExtraDiskSpaceRequired=250000000

[Dirs]
Name: "{app}"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

; NOTE: No [Files] section for the app itself — it is downloaded at
; install time by the [Code] section below instead of being embedded here.

[Registry]
Root: HKCU; Subkey: "Software\Classes\NullABrowserHTML"; \
    ValueType: string; ValueData: "NullA Browser HTML"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\NullABrowserHTML"; \
    ValueType: string; ValueName: "URL Protocol"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\NullABrowserHTML\DefaultIcon"; \
    ValueType: string; ValueData: "{app}\{#MyAppExeName},0"
Root: HKCU; Subkey: "Software\Classes\NullABrowserHTML\shell\open\command"; \
    ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA"; \
    ValueType: string; ValueData: "NullA Browser"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\DefaultIcon"; \
    ValueType: string; ValueData: "{app}\{#MyAppExeName},0"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\shell\open\command"; \
    ValueType: string; ValueData: """{app}\{#MyAppExeName}"""
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\Capabilities"; \
    ValueType: string; ValueName: "ApplicationName"; ValueData: "NullA Browser"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\Capabilities"; \
    ValueType: string; ValueName: "ApplicationDescription"; ValueData: "Fast for freedom"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\Capabilities\URLAssociations"; \
    ValueType: string; ValueName: "http"; ValueData: "NullABrowserHTML"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\Capabilities\URLAssociations"; \
    ValueType: string; ValueName: "https"; ValueData: "NullABrowserHTML"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\Capabilities\FileAssociations"; \
    ValueType: string; ValueName: ".htm"; ValueData: "NullABrowserHTML"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\Capabilities\FileAssociations"; \
    ValueType: string; ValueName: ".html"; ValueData: "NullABrowserHTML"
Root: HKCU; Subkey: "Software\RegisteredApplications"; \
    ValueType: string; ValueName: "NullA Browser"; \
    ValueData: "Software\Clients\StartMenuInternet\NullA\Capabilities"

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent; Check: ShouldLaunchNullA

[Code]
var
  DownloadPage: TDownloadWizardPage;
  VCRedistOK: Boolean;

procedure InitializeWizard;
begin
  DownloadPage := CreateDownloadPage(SetupMessage(msgWizardPreparing), SetupMessage(msgPreparingDesc), nil);
  VCRedistOK := True;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  if CurPageID = wpReady then begin
    DownloadPage.Clear;
    DownloadPage.Add('{#DownloadUrl}', 'NullA-Windows.zip', '');
    DownloadPage.Show;
    try
      try
        DownloadPage.Download;
        Result := True;
      except
        if DownloadPage.AbortedByUser then
          Log('Download aborted by user.')
        else
          SuppressibleMsgBox(AddPeriod(GetExceptionMessage), mbCriticalError, MB_OK, IDOK);
        Result := False;
      end;
    finally
      DownloadPage.Hide;
    end;
  end else
    Result := True;
end;

procedure UnzipWithShell(ZipPath, TargetPath: String);
var
  Shell, SourceItems, TargetFolder: Variant;
begin
  Shell := CreateOleObject('Shell.Application');
  SourceItems := Shell.NameSpace(ZipPath).Items;
  TargetFolder := Shell.NameSpace(TargetPath);
  // Flags: 4 = no progress dialog, 16 = respond "Yes to All" to any prompt
  TargetFolder.CopyHere(SourceItems, 4 + 16);
end;

function ExtractDownloadedZip(): Boolean;
var
  ZipPath, ExtractTemp, WrapperFolder: String;
  FindRec: TFindRec;
begin
  ZipPath := ExpandConstant('{tmp}\NullA-Windows.zip');
  ExtractTemp := ExpandConstant('{tmp}\NullA-extract');

  if not DirExists(ExtractTemp) then
    CreateDir(ExtractTemp);

  // Shell.Application's CopyHere runs asynchronously in some cases; give it
  // a moment to finish before checking the result.
  UnzipWithShell(ZipPath, ExtractTemp);
  Sleep(2000);

  WrapperFolder := ExtractTemp + '\NullA';
  Result := DirExists(WrapperFolder);

  if not Result then
  begin
    MsgBox('Extraction did not produce the expected "NullA" folder.' + #13#10 +
           'Looked for: ' + WrapperFolder, mbError, MB_OK);
    Exit;
  end;

  // Move everything out of the "NullA" wrapper folder and into {app},
  // since the archive contains a top-level "NullA/" directory.
  if FindFirst(WrapperFolder + '\*', FindRec) then
  begin
    try
      repeat
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') then
        begin
          if not RenameFile(WrapperFolder + '\' + FindRec.Name, ExpandConstant('{app}') + '\' + FindRec.Name) then
          begin
            MsgBox('Could not move: ' + FindRec.Name, mbError, MB_OK);
            Result := False;
          end;
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

function InstallVCRedist(): Boolean;
var
  RedistPath: String;
  ResultCode: Integer;
begin
  Result := True;
  RedistPath := ExpandConstant('{app}\vc_redist.x64.exe');

  if not FileExists(RedistPath) then
    Exit;

  if not Exec(RedistPath, '/install /quiet /norestart', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    MsgBox('Could not launch the Visual C++ Redistributable installer.' + #13#10 +
           'NullA Browser may fail to start until it is installed manually.', mbError, MB_OK);
    Result := False;
    Exit;
  end;

  case ResultCode of
    0, 1638, 3010: Result := True; // 0 = success, 1638 = already installed, 3010 = success, reboot required
  else
    begin
      MsgBox('The Visual C++ Redistributable installer returned an error (code ' + IntToStr(ResultCode) + ').' + #13#10 +
             'NullA Browser may fail to start until it is installed manually.', mbError, MB_OK);
      Result := False;
    end;
  end;
end;

function ShouldLaunchNullA(): Boolean;
begin
  Result := VCRedistOK;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    if not ExtractDownloadedZip() then
    begin
      MsgBox('Failed to extract the downloaded files. Please try running the installer again.', mbError, MB_OK);
      Exit;
    end;

    VCRedistOK := InstallVCRedist();
  end;
end;
