; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "NullA Browser"
#ifndef MyAppVersion
  #define MyAppVersion "0.0.0-dev"
#endif
#define MyAppPublisher "Electus Progressive Liberation Software"
#define MyAppURL "https://epls.itch.io/"
#define MyAppExeName "NullA.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

; Source files are now provided by build-installer.ps1, which downloads
; the release zip from GitHub and extracts it into this fixed folder.
#define SourceDir "dist\NullA"

#expr EmitLanguagesSection

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; DO NOT CHANGE — must stay fixed so existing installs can be updated in place.
AppId={{842598F1-5A1C-45CC-91CD-AE6A7CCBF379}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=LICENSE.txt
OutputDir=dist
OutputBaseFilename=NullA Setup
SetupIconFile=resources\nulla_icon.ico
SolidCompression=yes
WizardStyle=modern

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#SourceDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKCU; Subkey: "Software\Classes\NullABrowserHTML"; \
    ValueType: string; ValueData: "NullA Browser HTML"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\NullABrowserHTML"; \
    ValueType: string; ValueName: "URL Protocol"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\NullABrowserHTML\DefaultIcon"; \
    ValueType: string; ValueData: "{app}\{#MyAppExeName},0"
Root: HKCU; Subkey: "Software\Classes\NullABrowserHTML\shell\open\command"; \
    ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA"; \
    ValueType: string; ValueData: "NullA Browser"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\DefaultIcon"; \
    ValueType: string; ValueData: "{app}\{#MyAppExeName},0"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\shell\open\command"; \
    ValueType: string; ValueData: """{app}\{#MyAppExeName}"""
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\Capabilities"; \
    ValueType: string; ValueName: "ApplicationName"; ValueData: "NullA Browser"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\Capabilities"; \
    ValueType: string; ValueName: "ApplicationDescription"; ValueData: "Fast for freedom"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\Capabilities\URLAssociations"; \
    ValueType: string; ValueName: "http"; ValueData: "NullABrowserHTML"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\Capabilities\URLAssociations"; \
    ValueType: string; ValueName: "https"; ValueData: "NullABrowserHTML"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\Capabilities\FileAssociations"; \
    ValueType: string; ValueName: ".htm"; ValueData: "NullABrowserHTML"
Root: HKCU; Subkey: "Software\Clients\StartMenuInternet\NullA\Capabilities\FileAssociations"; \
    ValueType: string; ValueName: ".html"; ValueData: "NullABrowserHTML"
Root: HKCU; Subkey: "Software\RegisteredApplications"; \
    ValueType: string; ValueName: "NullA Browser"; \
    ValueData: "Software\Clients\StartMenuInternet\NullA\Capabilities"

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
